let participants = [
  "malwxqzx",
  "julias_mii",
  "ninksxq",
  "alionka.kk",
  "l.savinka",
  "sonya.exq",
  "1novyy_",
  "ninksxq",
  "max_gav",
  "vereshchakodasha",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "l.rxxw",
  "yanka_12_",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "_yana.12",
  "_yana.12",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "marihka_kov16",
  "vikt_oria4593",
  "marihka_kov16",
  "_yana.12",
  "marihka_kov16",
  "vikt_oria4593",
  "marihka_kov16",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "_yana.12",
  "vikt_oria4593",
  "_yana.12",
  "vikt_oria4593",
  "vikt_oria4593",
  "marihka_kov16",
  "vikt_oria4593",
  "_yana.12",
  "vikt_oria4593",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "vikt_oria4593",
  "milanasuhostavskaya",
  "_yana.12",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "vikt_oria4593",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "milanasuhostavskaya",
  "_yana.12",
  "marihka_kov16",
  "_yana.12",
  "marihka_kov16",
  "_yana.12",
  "marihka_kov16",
  "_yana.12",
  "marihka_kov16",
  "_yana.12",
  "marihka_kov16",
  "_yana.12",
  "marihka_kov16",
  "marihka_kov16",
  "marihka_kov16",
  "_yana.12",
  "_yana.12",
  "marihka_kov16",
  "marihka_kov16",
  "vikt_oria4593",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "ann._qp",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "sil.andreyseat",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "nasoyaaaa",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "nasoyaaaa",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "szpiung",
  "szpiung",
  "szpiung",
  "szpiung",
  "szpiung",
  "szpiung",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "evelina.olehnovich",
  "ellakreiza",
  "ellakreiza",
  "ellakreiza",
  "ellakreiza",
  "ellakreiza",
  "ellakreiza",
  "ellakreiza",
  "logoped_inna_mogilev",
  "darkwis20_11",
  "angelina_alexandrovna67",
  "angelina_alexandrovna67",
  "angelina_alexandrovna67",
  "angelina_alexandrovna67",
  "angelina_alexandrovna67",
  "angelina_alexandrovna67",
  "angelina_alexandrovna67",
  "azamatiksorik780",
  "azamatiksorik780",
  "azamatiksorik780",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "vikt_oria4593",
  "silyuk1991",
  "silyuk1991",
  "silyuk1991",
  "silyuk1991",
  "mark132474",
  "sanwqwe103",
  "sanwqwe103",
  "sanwqwe103",
  "sanwqwe103",
  "sanwqwe103",
  "alesya.kisell",
  "alesya.kisell",
  "alesya.kisell",
  "alesya.kisell",
  "alesya.kisell",
  "alesya.kisell",
  "alesya.kisell",
  "stepchik_vlasik",
  "stepchik_vlasik",
  "stepchik_vlasik",
  "silyuk1991",
  "silyuk1991",
  "baton.xps",
  "baton.xps",
  "baton.xps",
  "baton.xps",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "_just.eed",
  "savaradik2011",
  "savaradik2011",
  "savaradik2011",
  "savaradik2011",
  "savaradik2011",
  "savaradik2011",
  "savaradik2011",
  "savaradik2011",
  "savaradik2011",
  "savaradik2011",
];

// async function loadParticipants() {
//   try {
//     const response = await fetch("participants.json");
//     const data = await response.json();
//     participants = data.participants || [];
//   } catch (e) {
//     console.error("Ошибка при загрузке участников:", e);
//   }
// }

async function drawWinner() {
  if (participants.length === 0) {
    document.getElementById("winner").innerText = "Нет участников.";
    return;
  }

  let winner = "";
  const displayDuration = 3000;
  const intervalDuration = 150;

  const intervalId = setInterval(() => {
    winner = participants[Math.floor(Math.random() * participants.length)];
    document.getElementById("winner").innerText = winner;
  }, intervalDuration);

  setTimeout(() => {
    clearInterval(intervalId);
    const winnerElement = document.getElementById("winner");
    winnerElement.innerHTML = `<b>${winner}</b>`;

    for (let i = 0; i < 5; i++) {
      setTimeout(() => {
        confetti({
          particleCount: 2000,
          spread: 700,
          origin: {
            x: Math.random(),
            y: Math.random() * 0.5,
          },
        });
      }, i * 200);
    }
  }, displayDuration);
}

// loadParticipants();

document.getElementById("drawButton").addEventListener("click", drawWinner);
